### ISSUE TITLE
"Hide scrollbars" doesn't remove the scrollbar

### ISSUE THREAD

**Issue by catb0t** [bazukas/obs-linuxbrowser#101]
Plugin version: HEAD
CEF: 01/24/2019 - 3.3578.1866.g8121366 / Chromium 71.0.3578.98 linux64 
OS: Ubuntu 18.10

Checking and unchecking the "Hide scrollbars" box doesn't remove (or change) the scrollbar.

**Comment by NexAdn** [comment]
Unfortunately I was unable to reproduce this error.

**Comment by catb0t** [comment]
It was a website's custom CSS3 scrollbar, oops
