### ISSUE TITLE
Error building on Manjaro Linux

### ISSUE THREAD

**Issue by gwennshinguji** [bazukas/obs-linuxbrowser#109]
I'm trying to install the obs-linuxbrowser package in pamac from the AUR but I keep getting errors. Running yay doesn't help either.

Here is what it has when I try to build it: https://pastebin.com/bDD8TmSd

Any help is appreciated.

**Comment by gwennshinguji** [comment]
Installing the obs-linuxbrowser-bin package seems to have fixed it, sorry for prematurely opening a thread.

**Comment by NexAdn** [comment]
Duplicate of #108.
