### ISSUE TITLE
Implement auto-reload on file change

### ISSUE THREAD

**Issue by bazukas** [bazukas/obs-linuxbrowser#11]
Missing feature from qtwebkit source

**Comment by kingargyle** [comment]
I had the same issue with the OBS Browser source, and they wouldn't implement the automatic reload.  However, a work around which should work with the linux CEF implementation as well is to add a bit of javascript to automatically force a refresh periodically.

      
      <script>
        function reload_page() {
            location.reload(true);
            setTimeout(reload_page,2000);
        }
        setTimeout(reload_page,2000);
      </script>

However, this forces things to reload when nothing has actually changed on the file system, so I would love to have the auto-reload when file change implemented.   It is the one item that is keeping me from migrating over to the new browser source.

**Comment by bazukas** [comment]
Implemented in latest release
