### ISSUE TITLE
CEF Issue with the latest release

### ISSUE THREAD

**Issue by AresAndy** [bazukas/obs-linuxbrowser#111]
linux distro: Manjaro
OBS version: 23.2.1-141-gdeaeb5e6
linuxbrowser version: 0.6.1

When using a linuxbrowser source (and also when restarting it) nothing is displayed, and in the terminal the binary `browser` complains about `cef_cookie_manager_create_manager` being undefined. I am using the manually build version of OBS because the prebuilt version for Arch does not cut it for me.

**Comment by NexAdn** [comment]
Duplicate of #110.
