### ISSUE TITLE
linuxbrowser fails to play alerts from a localhost URL, while external browsers (Firefox/Chromium) can

### ISSUE THREAD

**Issue by physixcat** [bazukas/obs-linuxbrowser#122]
Hello, I think I may have found an issue with the plugin. I'm trying to add a localhost browser source (URL being `http://localhost:25000/alerts?allow-audio-hooks=true`) to display alerts from a local instance of [PhantomBot](https://phantombot.tv/). However, the alerts never display on OBS, while they do on any other web browser.

My hypothesis is that the user is prompted for a username and password on trying to log in to some localhost ports (like the webutilities for PhantomBot), and obs-linuxbrowser does not know how to handle that dialog. I tried inputting the `http://localhost:25000/` URL, and then clicking Interact to click on the bot's dashboard, and instead of prompting me for the login details, it switches to showing nothing.

![2020-01-03-002048_1920x1080_scrot](https://user-images.githubusercontent.com/32757992/71709854-10147100-2dbf-11ea-9d6a-a57555f60a06.png)

![2020-01-03-002312_1920x1080_scrot](https://user-images.githubusercontent.com/32757992/71709887-3df9b580-2dbf-11ea-9835-32ebf31fd7fe.png)

**Comment by NexAdn** [comment]
How does PhantomBot request you to log in? If it's via a separate dialog box as it is being used in basic auth, this can't work as the browser is only sending the contents of the browser window back to the plugin.

**Comment by physixcat** [comment]
It's via a separate dialog box, yes. However, I have found that my hypothesis is probably wrong. I was able to pass the user and password through the URL in the following format:
`http://user:password@localhost:25000/alerts?allow-audio-hooks=true&allow-alerts=true`
This works in external browsers just fine, but it still does not let anything through on obs-linuxbrowser.

If it helps, this is the output from starting obs on the terminal, around when alerts are played
`[0103/143855.750479:INFO:CONSOLE(3)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: http://user:password@localhost:25000/common/js/jquery-ui/external/jquery/jquery.min.js (3)
[0103/143855.758532:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
[0103/143855.758643:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
[0103/143855.758909:INFO:CONSOLE(211)] "[object DOMException]", source: http://user:password@localhost:25000/alerts/js/index.js (211)`

**Comment by physixcat** [comment]
Well, it seems I got it working. I don't really have any clue which of the little solutions/tweaks that I tried did the trick, but in short - problem solved, I can play alerts through obs-linuxbrowser when sourced from localhost now. I'll chalk it up to user error, I guess. Sorry for bothering you
