### ISSUE TITLE
Why does obsproject/obs-browser work on Linux?

### ISSUE THREAD

**Issue by briandilley** [bazukas/obs-linuxbrowser#125]
Was curious why `obsproject/obs-browser` wouldn't work on linux.  I plan on using CEF for something else and would like to know.  Sorry for creating an issue, I didn't see another way to ask a general question.

**Comment by NexAdn** [comment]
I think this isn't something you should ask us, but rather the OBS team. I also cannot answer that question, but there is already a PR obsproject/obs-browser#166 to enable Linux support for the official obs-browser plugin. You might have a look into that.
