### ISSUE TITLE
/root/Downloads/cef_binary_3.2987.1601.gf035232_linux64/tests/cefclient/browser/client_types.h:12:21: fatal error: gtk/gtk.h: No such file or directory  #include <gtk/gtk.h>

### ISSUE THREAD

**Issue by startech60serve** [bazukas/obs-linuxbrowser#13]
Just got to love linux :) ahh before ya ask ya loaded
 pkg-config --cflags --libs gtk+-3.0
-pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0

**Comment by bazukas** [comment]
When does this error happen? If during building of cef, then this is not the right place to open issues for that. In any case, I'll try to provide a couple of suggestions:
1. You probably need gtk2, not gtk3
2. Don't need that build target in the first place, so you can build just what we need using `make libcef_dll_wrapper`

**Comment by startech60serve** [comment]
seems we have a bit of a problem cant seem to find gtk2
dnf -y install build-essential libgtk2.0-dev
Last metadata expiration check: 2:37:14 ago on Mon Apr 24 17:09:07 2017.
No package build-essential available.
dnf -y install gtk2
Last metadata expiration check: 2:39:23 ago on Mon Apr 24 17:09:07 2017.
Package gtk2-2.24.31-2.fc25.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
and getting errors cant find 2.0  
on the cmake gtk+-2.0 was not found in the pkg-config search path

**Comment by bazukas** [comment]
Looks like you're using fedora, quick google search suggests that you'd need to install gtk2-devel.
Or just skip that part and use `make libcef_dll_wrapper` instead of just `make` as I suggested earlier.

**Comment by NexAdn** [comment]
`make libcef_dll_wrapper` won't create a shared object but just a static library
