### ISSUE TITLE
Linuxbrowser 

### ISSUE THREAD

**Issue by startech60serve** [bazukas/obs-linuxbrowser#14]
Linking CXX static library libcef_dll_wrapper.a [100%] Built target libcef_dll_wrapper
do a cmake with cmake -D CEF_DIR= /root/cef_binary_3.3029.1608.g27a32db_linux64
CMake Warning:
  Manually-specified variables were not used by the project:
    CEF_DIR
-- Build files have been written to: /root/cef_binary_3.3029.1608.g27a32db_linux64
[root@www build]# make
make: *** No targets specified and no makefile found.  Stop.
could you plz tell me why this isnt working pulling my hair out here

**Comment by bazukas** [comment]
Let's go from the start. You've already built libcef_dll_wrapper
1. `cd obs-linuxbrowser`
2. `mkdir build && cd build`
3. `cmake -D CEF_DIR=/root/cef_binary_3.3029.1608.g27a32db_linux64 ..` (don't forget the double dots)
4. `make`

**Comment by startech60serve** [comment]
thank you for all your help it just seems it dont want to play lol
[root@www build]# cmake -D CEF_DIR=/root/cef_binary_3.3029.1608.g27a32db_linux64 ..
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/obs-linuxbrowser-0.1.2/build
[root@www build]# make
Scanning dependencies of target obs-linuxbrowser
[  7%] Building C object CMakeFiles/obs-linuxbrowser.dir/src/plugin/main.c.o
/root/obs-linuxbrowser-0.1.2/src/plugin/main.c:17:24: fatal error: obs-module.h: No such file or directory
 #include <obs-module.h>
                        ^
compilation terminated.
CMakeFiles/obs-linuxbrowser.dir/build.make:62: recipe for target 'CMakeFiles/obs-linuxbrowser.dir/src/plugin/main.c.o' failed
make[2]: *** [CMakeFiles/obs-linuxbrowser.dir/src/plugin/main.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/obs-linuxbrowser.dir/all' failed
make[1]: *** [CMakeFiles/obs-linuxbrowser.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by startech60serve** [comment]
ok we search for the obs-module.h no luck 
got the pthread.h in /usr/include
got the stdio.h in /usr/include

**Comment by bazukas** [comment]
Do you have obs-studio installed in your system? If you do, use `-D OBS_INCLUDE=...` and `-D OBS_LIB=...` to point towards directories containing obs-module.h and libobs.so respectively.

**Comment by startech60serve** [comment]
well i think i found out why i cant find the obs-module.h I used a rpm t load it doing a dnf -y install obs-studio, And whe i tried to build it whit a yum install got a error on the 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find FFmpeg (missing: FFMPEG_AVCODEC_LIBRARIES
  FFMPEG_AVCODEC_INCLUDE_DIRS avcodec avdevice avutil avformat)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindFFmpeg.cmake:151 (find_package_handle_standard_args)
  deps/media-playback/CMakeLists.txt:3 (find_package)
but did find the obs-module.h in the build after the error so just about ready to give up on this lol

**Comment by startech60serve** [comment]
yum install libX11-devel mesa-libGL-devel libv4l-devel \
>           pulseaudio-libs-devel x264-devel freetype-devel \
>           fontconfig-devel libXcomposite-devel libXinerama-devel \
>           qt5-qtbase-devel qt5-qtx11extras-devel libcurl-devel \
>           systemd-devel ffmpeg
Redirecting to '/usr/bin/dnf install libX11-devel mesa-libGL-devel libv4l-devel pulseaudio-libs-devel x264-devel freetype-devel fontconfig-devel libXcomposite-devel libXinerama-devel qt5-qtbase-devel qt5-qtx11extras-devel libcurl-devel systemd-devel ffmpeg' (see 'man yum2dnf')
[root@www obs-studio]# cd build
[root@www build]# cmake -DUNIX_STRUCTURE=1 ..
-- OBS_VERSION: 18.0.1-67-g54281f2

**Comment by bazukas** [comment]
I don't quite understand, if you install obs-studio from the repositories you don't need to then build it yourself.

**Comment by startech60serve** [comment]
with the dnf -y install obs-studio there isnt a obs-module.h to be found searched the whole HD its not to be found try to build it and there is one dont understand it myself but cant seem to find the obs-studio.h.
the ffmpeg error is probably looking at openmeetings build  where we have it going. Dont mean to mix you up but im doing a good job at it to myself lol.

**Comment by startech60serve** [comment]
not only that there is no folder plugins there is plugin_config  /root/.config/obs-studio . Extract contents of the archive into $HOME/.config/obs-studio/plugins

**Comment by startech60serve** [comment]
I meant dir not folder

**Comment by startech60serve** [comment]
[root@www ~]# find / -name {obs-studio.h}
[root@www ~]# 
not there

**Comment by bazukas** [comment]
Look's like on fedora obs-studio has a separate 'obs-studio-devel' package that includes header files, you should install that.

**Comment by startech60serve** [comment]
dont know if you want all this info but it might help after installing obs-studio-devel' package
found the files and info i edit the CMakeLists.txt 
set(OBS_INCLUDE "/usr/include/obs" CACHE PATH "OBS Include Dir")
set(OBS_LIB "/usr/lib64" CACHE PATH "OBS Lib Dir")
set(CEF_DIR "/opt/cef" CACHE PATH "CEF Binary Release Dir")
did the cmake -D CEF_DIR=/root/cef_binary_3.3029.1611.g44e39a8_linux64 ..
did the make came up with 
[root@www build]# make
Scanning dependencies of target obs-linuxbrowser
[  7%] Building C object CMakeFiles/obs-linuxbrowser.dir/src/plugin/main.c.o
[ 15%] Building C object CMakeFiles/obs-linuxbrowser.dir/src/plugin/manager.c.o
[ 23%] Linking C shared module build/obs-linuxbrowser/bin/64bit/libobs-linuxbrowser.so
[ 23%] Built target obs-linuxbrowser
Scanning dependencies of target browser-subprocess
[ 30%] Building CXX object CMakeFiles/browser-subprocess.dir/src/browser/base64.cpp.o
[ 38%] Building CXX object CMakeFiles/browser-subprocess.dir/src/browser/browser-app.cpp.o
[ 46%] Building CXX object CMakeFiles/browser-subprocess.dir/src/browser/browser-client.cpp.o
[ 53%] Building CXX object CMakeFiles/browser-subprocess.dir/src/browser/browser.cpp.o
[ 61%] Linking CXX executable build/obs-linuxbrowser/bin/64bit/browser-subprocess
/usr/bin/ld: warning: libXss.so.1, needed by /root/cef_binary_3.3029.1611.g44e39a8_linux64/Release/libcef.so, not found (try using -rpath or -rpath-link)
/root/cef_binary_3.3029.1611.g44e39a8_linux64/Release/libcef.so: undefined reference to `XScreenSaverQueryVersion'
/root/cef_binary_3.3029.1611.g44e39a8_linux64/Release/libcef.so: undefined reference to `XScreenSaverSuspend'
/root/cef_binary_3.3029.1611.g44e39a8_linux64/Release/libcef.so: undefined reference to `XScreenSaverQueryExtension'
/root/cef_binary_3.3029.1611.g44e39a8_linux64/Release/libcef.so: undefined reference to `XScreenSaverQueryInfo'
/root/cef_binary_3.3029.1611.g44e39a8_linux64/Release/libcef.so: undefined reference to `XScreenSaverAllocInfo'
collect2: error: ld returned 1 exit status
CMakeFiles/browser-subprocess.dir/build.make:173: recipe for target 'build/obs-linuxbrowser/bin/64bit/browser-subprocess' failed
make[2]: *** [build/obs-linuxbrowser/bin/64bit/browser-subprocess] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/browser-subprocess.dir/all' failed
make[1]: *** [CMakeFiles/browser-subprocess.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
So to fix this dnf install libXScrnSaver libXScrnSaver-devel
[root@www build]# make
[ 23%] Built target obs-linuxbrowser
[ 30%] Linking CXX executable build/obs-linuxbrowser/bin/64bit/browser-subprocess
[ 61%] Built target browser-subprocess
Scanning dependencies of target browser
[ 69%] Building CXX object CMakeFiles/browser.dir/src/browser/base64.cpp.o
[ 76%] Building CXX object CMakeFiles/browser.dir/src/browser/browser-app.cpp.o
[ 84%] Building CXX object CMakeFiles/browser.dir/src/browser/browser-client.cpp.o
[ 92%] Building CXX object CMakeFiles/browser.dir/src/browser/browser.cpp.o
[100%] Linking CXX executable build/obs-linuxbrowser/bin/64bit/browser
[100%] Built target browser
now i just got to find out where to make the install  to so it will be in the menu on the obs
but i thought you might like to have the info and thank for all your help (still have the install to figure out lol)

**Comment by bazukas** [comment]
Glad you could figure that out, just a couple of things:
1. You don't need to edit CMakeLists.txt, just setting the variable during cmake compilation would be enough, in your case:
`cmake -D CEF_DIR=/root/cef_binary_3.3029.1611.g44e39a8_linux64  -D OBS_LIB=/usr/lib64 ..`

2. To install the plugin just run `make install` and it will copy the plugin files to $HOME/.config/obs-studio/plugins
