### ISSUE TITLE
Chrome remote debugger doesn't work properly

### ISSUE THREAD

**Issue by DDRBoxman** [bazukas/obs-linuxbrowser#17]
I enabled the remote debuger by setting the port I want to use in the CEF Settings in src/browser/browser.cpp
```
settings.remote_debugging_port = 5000;
```

When I load http://localhost:5000 in chrome I see the page that is currently loaded in the browser plugin. Clicking on it navigates to the page but the dev tools don't open up and show me the remote page.

I'll need this to track down what's going on with #16

**Comment by bazukas** [comment]
Thank you for looking into this. Devtools pak was missing in cef resouces dir, I fixed it in latest commit and it should be working now.

Also probably good idea to allow setting remote debug port from source properties, so leave this issue open until I implement that.

**Comment by bazukas** [comment]
You can now set debugging port using command-line arguments option in the plugin
