### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by LiamDawe** [bazukas/obs-linuxbrowser#18]
So the patents surrounding MP3 expired recently didn't they? Is there any other legal reason as to not bake in MP3 support in the downloadable builds?

**Comment by bazukas** [comment]
I'm looking into that. Main problem is that in order to enable proprietary codecs support, you need to build CEF from scratch and if spotify doesn't start providing builds with them enabled (probably not) I'll have to do that on my local machine.

**Comment by NexAdn** [comment]
Patents 5,924,060 and 5,703,999 are not expired (https://madfileformatscience.garymcgath.com/2016/04/05/mp3patent/). You should wait until December if you want to provide a prebuild CEF with MP3 support.

**Comment by LiamDawe** [comment]
Not according to this https://twitter.com/icculus/status/853772981344063489 (read the replies) people keep getting dates wrong.

**Comment by NexAdn** [comment]
Okay, thanks.

**Comment by bazukas** [comment]
Ok, next release will ship with mp3

**Comment by LiamDawe** [comment]
Awesome news, as further confirmation, Fedora Linux will bake MP3 in as well: http://phoronix.com/scan.php?page=news_item&px=Full-MP3-Support-In-Fedora

So it's fine 👍

**Comment by bazukas** [comment]
MP3 enabled build is live: https://github.com/bazukas/obs-linuxbrowser/releases/tag/0.2.0

I'm gonna leave this thread open to see if any people have problems with the build, so let me know if stuff works/notworks
