### ISSUE TITLE
Interact

### ISSUE THREAD

**Issue by ThePooN** [bazukas/obs-linuxbrowser#2]
Do you think you'll implement Interact any time soon? Would be very handy for me, I would actually have an use for it tomorrow but no urge, I can do without it.

**Comment by bazukas** [comment]
I'll start working on interaction soon, can't make any promises about the date though.

**Comment by ThePooN** [comment]
That's fine, thanks.

**Comment by bazukas** [comment]
It just came to my attention that there is an aur package for the obs-qtwebkit and looks like you're the author? Thanks for you work. If you're going to make one for this plugin as well, I'd appreciate it a lot. Also should add it in README.

**Comment by ThePooN** [comment]
Yes, that's me! I'll work on doing one for this too (as I've already been asked in the comments), but that may take time as I'll also need to work on a CEF AUR package since there are none in AUR.

**Comment by bazukas** [comment]
Do you plan to make a package for building CEF from scratch? I've read that it takes a lot of time even on good computers since you'd need to compile entire chromium codebase.

**Comment by ThePooN** [comment]
I think I'll provide two: one to download and extract from automated builds, and another one to compile with mp3 support.

**Comment by bazukas** [comment]
That sounds nice

**Comment by bazukas** [comment]
I pushed an initial implementation of interactivity. Still need to fix some weird things like context menus
and some keycodes not working.

**Comment by ThePooN** [comment]
Good enough, I just need mouse clicks for tomorrow!! Thanks a ton!
