### ISSUE TITLE
OBS Crashes on startup

### ISSUE THREAD

**Issue by TheRActivator** [bazukas/obs-linuxbrowser#20]
https://gist.github.com/TheRActivator/67f3b9cc4fc7532d7ec2562db0c3c1d1

Does not happen when I don't have this plugin installed.

**Comment by TheRActivator** [comment]
Not sure why it says "OBS 0.0.1", I have the latest version (1.7)

**Comment by bazukas** [comment]
Latest version is 18.0.1...
How did you install the OBS?

**Comment by TheRActivator** [comment]
https://github.com/jp9000/obs-studio/wiki/Install-Instructions#linux
Exactly like this, also I plucked that number from memory so I could easily have 1.8

**Comment by bazukas** [comment]
Exactly like what? Did you install from official ppa?

**Comment by TheRActivator** [comment]
Yes.

**Comment by TheRActivator** [comment]
```
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt-get update && sudo apt-get install obs-studio
```

**Comment by bazukas** [comment]
Can you remove the plugin for now, launch obs and tell me what version it says OBS is in the window title?

**Comment by TheRActivator** [comment]
0.0.1
Why are we going over this? It's common bug it seems

**Comment by bazukas** [comment]
Well your log suggests that libobs version that my plugin is compiled against and libobs that's installed on your system are not compatible, and your obs reporting that its version is 0.0.1 is the only clue I have

**Comment by bazukas** [comment]
Could you show me the output of `dpkg -l obs-studio`

**Comment by TheRActivator** [comment]
0.14.2+dfsg1 as the version, strangely... Even if I have an outdated version I have no idea how to update it because apt-show-versions says it's uptodate

**Comment by TheRActivator** [comment]
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  obs-studio     0.14.2+dfsg1 amd64        recorder and streamer for live vi

**Comment by bazukas** [comment]
Seems like you installed obs-studio debian package.
Make sure you added the ppa and then try purging `sudo apt-get purge obs-studio`
And reinstall it

**Comment by TheRActivator** [comment]
o_O somehow I installed the debian package...
I swear I did it correctly... Well, it works now
