### ISSUE TITLE
`GLIBCXX_3.4.21' not found on Debian Jessie

### ISSUE THREAD

**Issue by kadogo** [bazukas/obs-linuxbrowser#22]
Hello,
When I try to use your plugin I don't see the website that I "load".

If I check the OBS log is see the following line

```
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found 
```

I build OBS manually and I can capture desktop and games.
If you need the complete log, don't hesitate to ask it.

Have a nice day, cheers.

**Comment by NexAdn** [comment]
https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
Does this help?

**Comment by kadogo** [comment]
@NexAdn 

* libstdc++6 is already installed
* I tried an upgrade / dist-upgrade without succes

I don't have tried the ppa because I try to avoid upgrading libs that are not official for Debian and risk to break my system.

It's ok if it cannot be fix because a version issue, it's more to know if the problem is my version of libstdc++6 or something else.

**Comment by bazukas** [comment]
Hey @kadogo 

If you build the plugin yourself, you shouldn't have any problems (shouldn't be too difficult, since you've already built OBS).

I'll try to target more common GLIBC versions in the next release.

**Comment by bazukas** [comment]
Latest release is linked statically to libstdc++, so this problem should be solved
