### ISSUE TITLE
Option to Hide Scroll Bars

### ISSUE THREAD

**Issue by kingargyle** [bazukas/obs-linuxbrowser#24]
In the old obs-qtwebkit browser the side scroll bars would not be shown.  In the current linux-browser, I'm seeing scroll bars.

**Comment by kingargyle** [comment]
Actually it looks like a combination of these two command line arguments work.
--hide-scrollbars
--disable-overlay-scrollbar

However, I had to exit out of OBS and then restart them to get it to apply.  Clicking the restart browser button did not apply the changes.

**Comment by bazukas** [comment]
Hey there. I was investigating the issue of restarting browser not applying the command like arguments, but the are applied on restart.

One thing I discovered is that those options don't seem to take effect at all for me. Apparently --hide-scrollbars was removed a while ago. Can you check on your end again?

In any case, you should be able to remove the scrollbars using css.

**Comment by kingargyle** [comment]
Yeah those options stopped working for me.  I can also use a Crop Filter to cut off the scroll bars as well.  It would be nice though to have a check box that allows for the removal of the scroll bars.   I may just resort to a crop filter as I really don't feel like messing around with the CSS.

**Comment by bazukas** [comment]
Implemented an option in latest release

**Comment by kingargyle** [comment]
Thanks!
