### ISSUE TITLE
libatomic.so.1 Issue

### ISSUE THREAD

**Issue by TrapCosmos** [bazukas/obs-linuxbrowser#26]
Hello bazukas,

Sorry, I believe this isn't so much an issue on your part it's an issue on ours. However, we don't know how to resolve it so we've resorted to asking you.

"path/to/browser: error while loading libraries: libatomic.so.1: cannot open shared object file: No such file or directory"

Previously, 0.1.2 loaded fine. However, updating to 2.0 resulted in this error.

Thank you for any insight you can give,
James.

**Comment by bazukas** [comment]
Hello there, seems like libatomic library package is missing in your system. What distribution are you using? Most likely you'll need to install a package called libatomic to resolve the issue.

**Comment by TrapCosmos** [comment]
Thank you for your fast response.

We are using Ubuntu Server 16.04 but using the Lubuntu Desktop.

I'm assuming libatomic is a new requirement as of 2.0?

Thanks once again,
James.

**Comment by bazukas** [comment]
Yes, the dependency on libatomic.so.1 was added in 0.2.0.
I'm not so sure about the "server" version of ubuntu, but it is present by default on most distributions.
Try searching for packages containing libatomic

**Comment by TrapCosmos** [comment]
Okay, so I've got ahead and installed libatonic1-alpha-cross and there is now a folder containing the libatomic.so.1, now... how do I get obs-linuxbrowser/CEF to recognize it? Do I move it to a specific folder or can I specify the location?

**Comment by bazukas** [comment]
If you installed a proper package, it should place the library in the correct location.. In any case, if you put it in /usr/lib/ it shoud work.

**Comment by TrapCosmos** [comment]
I appreciate the help, bazukas. 

I have put both "libatomic.so.1" (shortcut) and "libatomic.so.1.1.0" both of their file types are "shared library" and they are in "/usr/lib/" - yet they are still not recognised by CEF/obs-linuxbrowser.

For tonight, I am going to give up but will continue trying other things tomorrow.

Also, I used "libatonic1-alpha-cross" instead of "libatomic1" as "libatmoic1" doesn't appear to be supported in 16.04.

Thanks,
James.

**Comment by bazukas** [comment]
Unfortunately, I'm not sure I'll be able to help you with this any further.
I'd suggest considering switching to a regular Ubuntu 16.04, because I don't see a reason to have the "server" version, although I do understand that it shouldn't be a proposed solution for this kind of problem

**Comment by kitling** [comment]
@TrapCosmos The `*-alpha-cross` packages are for cross compiling to a different architecture. In fact, none of the `*-*-cross` packages will produce the results you are looking for. You should uninstall `libatomic1-alpha-cross` and undo any other changes you made having to do with `libatomic`.

From a quick package search online, `libatomic1` appears to be the correct package. It is indeed supported in 16.04, so far as I can tell. Could you share why you thought it was unsupported in 16.04?

**Comment by TrapCosmos** [comment]
Sorry for the late response, I was not keeping up to date on this issue.

**Comment by TrapCosmos** [comment]
Sorry for the late response I want not keeping up to date on this issue.

Hey kitling,

I get this error when using apt-get to install the library: "libatomic1 : Depends: gcc-5-base (- 5.3.1-14-ubuntu2) but 5.4.0-6ubuntu1-16.04.4 is to be installed"

Thanks for any insight you can give,
James.

**Comment by kitling** [comment]
... huh, so it's force depending on an older version of gcc than is installed/available?

**Comment by kitling** [comment]
Could you run an `apt update,` `apt upgrade`, `apt dist-upgrade`, and perhaps an `apt-get install --only-upgrade gcc-5-base` before trying again?

**Comment by TrapCosmos** [comment]
Thanks kitling for the suggestions but after running each of these commands the same issue occurs.

**Comment by kitling** [comment]
Could you run `apt-cache policy libatomic1` and paste the output?

**Comment by TrapCosmos** [comment]
https://imgur.com/a/muvO3

**Comment by kitling** [comment]
Are the `xenial-updates` and `xenial-security` repositories enabled in your `/etc/apt/sources.list`? If they aren't, I would reccomend enabling them.

**Comment by TrapCosmos** [comment]
Hm, so I just uncommented all the commented repositories then once again attempted to install libatomic1, but the issue persists.

**Comment by kitling** [comment]
Did you do an `apt update` before attempting to reinstall and after uncommenting the repositories?

**Comment by TrapCosmos** [comment]
Yes, I did. However, there were some 404 messages and stuff that generally didn't look too positive, mind I did just uncomment all of them though.

**Comment by bazukas** [comment]
Hey @TrapCosmos, were you able to come up to a solution with your problem?
