### ISSUE TITLE
Browser zoom level

### ISSUE THREAD

**Issue by rikkertkoppes** [bazukas/obs-linuxbrowser#28]
Very nice work!

I am looking to set the zoom level for the browser. This is because I can get better result by zooming the browser than setting a small size and scaling the result

I tried to set parameters to --ash-host-window-bounds=1280x720*2 (fount here: https://peter.sh/experiments/chromium-command-line-switches/#ash-host-window-bounds), but that did not seem to work

**Comment by bazukas** [comment]
Implemented an option in latest release
