### ISSUE TITLE
Refresh page after transition

### ISSUE THREAD

**Issue by S-Marais** [bazukas/obs-linuxbrowser#39]
A little explanation: I use streamelements overlays. one of them is set to be my starting overlay showing a countdown before the stream actually starts. When I launch obs the page is loaded and the countdown goes down even tho I'm not streaming. When I actually start to stream I have to prepare myself:
charge page in obs studio mode go into the scene source, load the properties page, refresh the page and rapidly close the properties page transition the scene and start the stream.

It would be a lot easier to just have a checkbox to refresh the page when the scene get's active.

**Comment by bazukas** [comment]
Implemented by 64be2db10c330e442272db5c661cb39c3e6340ef
