### ISSUE TITLE
Custom CSS Support

### ISSUE THREAD

**Issue by ThePooN** [bazukas/obs-linuxbrowser#4]
Custom CSS Support is the last thing I need before switching from obs-qtwebkit. Also, I would qualify that as a bit urgent as you have deprecated obs-qtwebkit and yet this is a missing feature.

**Comment by bazukas** [comment]
I implemented custom css in the last patch. I would like to confirm that everything works at least on your end.

**Comment by ThePooN** [comment]
Sorry for the late answer! It seems there's sort of a problem with loading custom system fonts, some default font is used instead (for example, Exo 2 is installed on my system, works with obs-qtwebkit, but not with obs-linuxbrowser). I had to link it into my CSS with Google Fonts to make it work.

Not sure what's the issue there (if it's seperate or not or anything), so I'll leave this open.

**Comment by NexAdn** [comment]
Is this issue still relevant?

**Comment by ThePooN** [comment]
I use browser source all the time and despite having done new stuff since I reported this bug, I don't think I've had to import fonts I used into CSS each time.  
I guess it has been fixed upstream.

**Comment by NexAdn** [comment]
Well, I don't remember us having done anything about it. Neither do I remember having experienced any CSS problems. Might as well have been a bug in CEF itself.
