### ISSUE TITLE
Streamlabs Widgets have to be refresh manually at OBS startup

### ISSUE THREAD

**Issue by JeffHoogland** [bazukas/obs-linuxbrowser#42]
When I start OBS often my widgets from StreamLabs.com often do not load / display until I open the browser source plugin properties and manually click reload.

Is this an issue on streamlab's side or this plugin?

**Comment by ThePooN** [comment]
I'm experiencing the same issue; also occurs with Discord StreamKit and KapChat. Likely related to network. Although, it does not happen every time I start OBS on my end.

**Comment by bazukas** [comment]
Hey, I was trying to reproduce on my end and I'm not having any luck. What kind of widgets do you use?

Also, could you capture the logs after opening obs from console? Logs from the obs run when the widgets don't load.

**Comment by NexAdn** [comment]
Have you tried to build obs-linuxbrowser with the current master [(64be2db1)?](https://github.com/bazukas/obs-linuxbrowser/commit/64be2db10c330e442272db5c661cb39c3e6340ef) I have implemented a feature to auto reload the browser on scene activation, maybe this is what you need.

**Comment by JeffHoogland** [comment]
I'll try updating to the latest source and see if that helps. If it doesn't I'll post the log next time it happens.

It happens with all the widgets infrequently here. Chat box, alert box, cheer cup, and event list from streamlabs.com

**Comment by ThePooN** [comment]
Not on computer atm so can't provide logs; but I think I'm using the binaries you provide. It might be a Chromium issue. On Discord StreamKit, it loads and I can see the frame, but it seems to fail to connect to the Discord servers.

**Comment by bazukas** [comment]
Fixed in the latest release
