### ISSUE TITLE
Streamlabs/Muxy.io widgets don't work?

### ISSUE THREAD

**Issue by JeffHoogland** [bazukas/obs-linuxbrowser#43]
This is listed in the README.

I use this plugin exclusively with Streamlabs widgets (cheer cup, alert box, and event list) - all of them work as far as I have tried. Is this from an old release and should be removed or is it referring to something specific from these sites that does not work?

**Comment by bazukas** [comment]
Audio alerts on those widgets don't work if you build the plugin yourself because public cef releases don't provide mp3 support

**Comment by NexAdn** [comment]
MP3 should've been included in Chromium 62 / CEF 3.3202

**Comment by JeffHoogland** [comment]
Audio is working as expected from streamlabs here with the latest download of the plugin. Also worked for me with previous iterations.

**Comment by bazukas** [comment]
@NexAdn audio in streamlabs doesn't work for me if I compile against cef 3202 from spotify.

@JeffHoogland do you mean that you compile the plugin yourself using cef releases from spotify and the audio works?

**Comment by JeffHoogland** [comment]
No. Using the default source or compiled version from this repo audio works from streamlabs for me on Ubuntu 16.04

**Comment by RytoEX** [comment]
[MP3 support as a _non-proprietary_ codec](https://bugs.chromium.org/p/chromium/issues/detail?id=746579) won't arrive in CEF/Chromium until M64, meaning the branch after 3239.

As I understand it, the commits for it missed the branch date for M62 (3202) and M63 (3239).

**Comment by bazukas** [comment]
@RytoEX Thank you for the info.

@JeffHoogland mp3 is enabled in binary releases provided by me and currently disabled if you're building plugin against public releases of cef provided by spotify. Audio in streamlabs doesn't work if you're building the plugin yourself.
