### ISSUE TITLE
Install Issues Please help

### ISSUE THREAD

**Issue by jinutm1** [bazukas/obs-linuxbrowser#44]
Hi,

I tried to install the obs linux browser. I am confused with the cmake command. never done before. in this code;
cmake -D CEF_DIR=<path to your cef dir> .. You might need to also set OBS_INCLUDE and/or OBS_LIB build variables
How I set the path. My CEF directory is /Videos/CEF. I tried cmake -D CEF_DIR=</Videos/CEF> and cmake -D CEF_DIR=/Videos/CEF and cmake -D CEF_DIR=/home/myusername/Videos/CEF and cmake -D CEF_DIR=</home/myusername/Videos/CEF>
All comes with error. there is no directory. Please guide me. I need this plugin. Very urgent. 

Jinu

**Comment by bazukas** [comment]
Hello. Is there a reason you're trying to build the plugin instead of using prebuilt binaries? Have you tried following the Installation instructions in README?

**Comment by NexAdn** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=obs-linuxbrowser
Look into the build() function and compare it with your commands. Maybe you can spot the mistake.

**Comment by bazukas** [comment]
Closed due to lack of response
