### ISSUE TITLE
Ubuntu 17.10

### ISSUE THREAD

**Issue by LordGault** [bazukas/obs-linuxbrowser#45]
Hi, I'm using Ubuntu 17.10 and the plugin doesn't work. Any ideas?

**Comment by NexAdn** [comment]
This description could not have been any more verbose.

**Comment by LordGault** [comment]
I just installed Ubuntu 17.10 and it just doesn't work. Follow the installation steps. The funny thing is that LinuxMint 18.03 does work. I checked it on my laptop with LinuxMint 18.03.

**Comment by JeffHoogland** [comment]
That probably means you are missing some dependencies on your Ubuntu 17.10 system. Make sure you have all the multimedia codecs and such installed.

**Comment by LordGault** [comment]
> That probably means you are missing some dependencies on your Ubuntu 17.10 system. Make sure you have all the multimedia codecs and such installed.

Some easy way to check for possible dependencies?

**Comment by JeffHoogland** [comment]
The dependencies you need likely depend on the file format being served up from whatever website you are trying to capture from.

**Comment by bazukas** [comment]
Hey LordGault. Could you provide a log?

**Comment by LordGault** [comment]
> Hey LordGault. Could you provide a log?
Where is the log file located?

**Comment by LordGault** [comment]
`16:27:23.765: CPU Name: AMD FX(tm)-8320 Eight-Core Processor
16:27:23.765: CPU Speed: 4200.000MHz
16:27:23.765: Physical Cores: 4, Logical Cores: 8
16:27:23.765: Physical Memory: 16071MB Total, 5959MB Free
16:27:23.765: Kernel Version: Linux 4.13.0-21-generic
16:27:23.765: Distribution: "Pop!_OS" "17.10"
16:27:23.766: Portable mode: false
16:27:23.787: OBS 20.1.0 (linux)
16:27:23.787: ---------------------------------
16:27:23.787: ---------------------------------
16:27:23.787: audio settings reset:
16:27:23.787: 	samples per sec: 44100
16:27:23.787: 	speakers:        2
16:27:23.797: ---------------------------------
16:27:23.797: Initializing OpenGL...
16:27:23.924: OpenGL version: 3.2.0 NVIDIA 384.90
16:27:23.936: ---------------------------------
16:27:23.936: video settings reset:
16:27:23.936: 	base resolution:   1920x1080
16:27:23.936: 	output resolution: 1280x720
16:27:23.936: 	downscale filter:  Bicubic
16:27:23.936: 	fps:               60/1
16:27:23.936: 	format:            NV12
16:27:23.937: Audio monitoring device:
16:27:23.937: 	name: Por defecto
16:27:23.937: 	id: default
16:27:23.937: ---------------------------------
16:27:23.963: No blackmagic support
16:27:24.002: NVENC supported
16:27:24.012: os_dlopen(libvlc.so.5->libvlc.so.5): libvlc.so.5: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
16:27:24.012: 
16:27:24.012: Couldn't find VLC installation, VLC video source disabled
16:27:24.013: Failed to load 'es-ES' text for module: 'libobs-linuxbrowser.so'
16:27:24.013: ---------------------------------
16:27:24.013:   Loaded Modules:
16:27:24.013:     libobs-linuxbrowser.so
16:27:24.013:     vlc-video.so
16:27:24.013:     text-freetype2.so
16:27:24.013:     rtmp-services.so
16:27:24.013:     obs-x264.so
16:27:24.013:     obs-transitions.so
16:27:24.013:     obs-outputs.so
16:27:24.013:     obs-libfdk.so
16:27:24.013:     obs-filters.so
16:27:24.013:     obs-ffmpeg.so
16:27:24.013:     linux-v4l2.so
16:27:24.013:     linux-pulseaudio.so
16:27:24.013:     linux-jack.so
16:27:24.013:     linux-decklink.so
16:27:24.013:     linux-capture.so
16:27:24.013:     linux-alsa.so
16:27:24.013:     image-source.so
16:27:24.013:     frontend-tools.so
16:27:24.013: ---------------------------------
16:27:24.013: ==== Startup complete ===============================================
16:27:24.013: Service '' not found
16:27:24.015: All scene data cleared
16:27:24.015: ------------------------------------------------
16:27:24.021: pulse-input: Server name: 'pulseaudio 10.0'
16:27:24.021: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
16:27:24.021: pulse-input: Started recording from 'alsa_output.pci-0000_00_14.2.analog-stereo.monitor'
16:27:24.024: pulse-input: Server name: 'pulseaudio 10.0'
16:27:24.025: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
16:27:24.025: pulse-input: Started recording from 'alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201511-00.analog-stereo'
16:27:24.031: Switched to scene 'Escena'
16:27:24.031: ------------------------------------------------
16:27:24.031: Loaded scenes:
16:27:24.031: - scene 'Escena':
16:27:24.031:     - source: 'StreamLabs' (linuxbrowser-source)
16:27:24.031: ------------------------------------------------
16:27:24.529: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
16:27:25.343: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
16:31:07.303: adding 23 milliseconds of audio buffering, total audio buffering is now 69 milliseconds
16:36:25.509: adding 23 milliseconds of audio buffering, total audio buffering is now 92 milliseconds`

I think this is it.

**Comment by LordGault** [comment]
Sorry, it wasn't Ubuntu 17.10 was Pop! OS 17.10. Now you have a log with Ubuntu 17.10 where it still doesn't work.

18:25:30.901: CPU Name: AMD FX(tm)-8320 Eight-Core Processor
18:25:30.901: CPU Speed: 1400.000MHz
18:25:30.902: Physical Cores: 4, Logical Cores: 8
18:25:30.902: Physical Memory: 16071MB Total, 11123MB Free
18:25:30.902: Kernel Version: Linux 4.13.0-21-generic
18:25:30.902: Distribution: "Ubuntu" "17.10"
18:25:30.903: Portable mode: false
18:25:30.926: OBS 20.1.0 (linux)
18:25:30.926: ---------------------------------
18:25:30.926: ---------------------------------
18:25:30.926: audio settings reset:
18:25:30.926: 	samples per sec: 44100
18:25:30.926: 	speakers:        2
18:25:30.937: ---------------------------------
18:25:30.937: Initializing OpenGL...
18:25:31.045: OpenGL version: 3.2.0 NVIDIA 384.90
18:25:31.055: ---------------------------------
18:25:31.055: video settings reset:
18:25:31.055: 	base resolution:   1920x1080
18:25:31.055: 	output resolution: 1280x720
18:25:31.055: 	downscale filter:  Bicubic
18:25:31.055: 	fps:               60/1
18:25:31.055: 	format:            NV12
18:25:31.056: Audio monitoring device:
18:25:31.056: 	name: Por defecto
18:25:31.056: 	id: default
18:25:31.056: ---------------------------------
18:25:31.072: No blackmagic support
18:25:31.117: NVENC supported
18:25:31.127: VLC found, VLC video source enabled
18:25:31.128: Failed to load 'es-ES' text for module: 'libobs-linuxbrowser.so'
18:25:31.128: ---------------------------------
18:25:31.128:   Loaded Modules:
18:25:31.128:     libobs-linuxbrowser.so
18:25:31.128:     vlc-video.so
18:25:31.128:     text-freetype2.so
18:25:31.128:     rtmp-services.so
18:25:31.128:     obs-x264.so
18:25:31.128:     obs-transitions.so
18:25:31.128:     obs-outputs.so
18:25:31.128:     obs-libfdk.so
18:25:31.128:     obs-filters.so
18:25:31.128:     obs-ffmpeg.so
18:25:31.128:     linux-v4l2.so
18:25:31.128:     linux-pulseaudio.so
18:25:31.128:     linux-jack.so
18:25:31.128:     linux-decklink.so
18:25:31.128:     linux-capture.so
18:25:31.128:     linux-alsa.so
18:25:31.128:     image-source.so
18:25:31.128:     frontend-tools.so
18:25:31.128: ---------------------------------
18:25:31.128: ==== Startup complete ===============================================
18:25:31.129: Service '' not found
18:25:31.131: All scene data cleared
18:25:31.131: ------------------------------------------------
18:25:31.136: pulse-input: Server name: 'pulseaudio 10.0'
18:25:31.137: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
18:25:31.137: pulse-input: Started recording from 'alsa_output.pci-0000_00_14.2.analog-stereo.monitor'
18:25:31.139: pulse-input: Server name: 'pulseaudio 10.0'
18:25:31.139: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
18:25:31.140: pulse-input: Started recording from 'alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201511-00.analog-stereo'
18:25:31.150: Switched to scene 'Escena'
18:25:31.150: ------------------------------------------------
18:25:31.150: Loaded scenes:
18:25:31.150: - scene 'Escena':
18:25:31.150:     - source: 'Streamlabs' (linuxbrowser-source)
18:25:31.150: ------------------------------------------------
18:25:31.692: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
18:25:33.597: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds

**Comment by NexAdn** [comment]
Linuxbrowser seems to load as expected. I have a similar issue with some CEF versions. It appears sometimes when I update my CEF installation. The current version which is working for me is 3.3239.1709.

**Comment by LordGault** [comment]
Yeah, I solved the problem by changing distribution :) The truth is that Ubuntu 17.10 has given me many more mistakes and I decided to change. Now I am with Manjaro KDE and I am very satisfied. Thank you.

**Comment by LordGault** [comment]
I found the glitch. Ubuntu 17.10 does not have libgconf-2-4 libraries installed. That proved that appimage applications didn't work either. Once the library is installed, everything works perfectly.

**Comment by bazukas** [comment]
Thank you for the info, I'll need to add CEF dependencies to README
