### ISSUE TITLE
obs-websocket support

### ISSUE THREAD

**Issue by mjc666** [bazukas/obs-linuxbrowser#46]
Any chance on adding support for [obs-websocket](https://github.com/Palakis/obs-websocket)?

I think all that would have to be done would be to change your plugin id from "linuxbrowser_source" to "browser_source".  I tested this myself and it seems to work ok.

**Comment by NexAdn** [comment]
We should not change the plugin id to make obs-linuxbrowser look like obs-browser. In case obs-linuxbrowser has some missing or extra functionality compared to obs-browser, problems can occur and it depends on how robust the implementation of obs-websocket is, if such problems can make the plugins or even the whole OBS session instable.

You should better open an issue at obs-websocket describing your feature request.

**Comment by NexAdn** [comment]
Closed as the issue has been resolved in Palakis/obs-websocket#360
