### ISSUE TITLE
Cache location/dir name in case of multiple instances

### ISSUE THREAD

**Issue by VasilyPechersky** [bazukas/obs-linuxbrowser#49]
Hi !
I am using multiple instances of obs-studio, launched from different users.
The problem is, that plugin creates dir in /tmp/linuxbrowser-cache with permission of first user, started plugin. Other users cannot use cache.

Can you please set name like /tmp/linuxbrowser-cache-$userid or place it in /home/$userid/.cache of the user. 

Thank you very much !

**Comment by bazukas** [comment]
Hello. Yes, I'll move the cache directory to $HOME/.cache/obs-linuxbrowser. Also will need to find a way to preserve cache dirs for each instance between obs launches.

**Comment by ponymedia** [comment]
Hi! amazing, I was just looking into this issue. i'm running ubunto... will it be released in next update?
Thank you so much Vasily and of course, bazukas!

**Comment by NexAdn** [comment]
Fixed.
