### ISSUE TITLE
Did not show up in the OBS

### ISSUE THREAD

**Issue by egordorichev** [bazukas/obs-linuxbrowser#5]
Hello!
I'm on linux, with OBS 1.18.0
Downloaded the release, and copied it contents to the obs folder.
But the plugin did not show up in the menu.

How do I fixed it?

**Comment by NuKT** [comment]
It shows up as »Linux Browser« and works fine. Maybe you just haven't recognized it.

**Comment by bazukas** [comment]
Hey there. After copying, inside ~/.config/obs-studio/plugins you should see "obs-linuxbrowser" dir. And inside that dir there should be "bin", "data" and "cache". Does it look like that?

**Comment by egordorichev** [comment]
Ok, great. Got it. It did not create plugin directory. After creating it my self, it showed up. Thanks!
