### ISSUE TITLE
OBS Studio doesn't start when obs-linuxbrowser is installed

### ISSUE THREAD

**Issue by SacredWKnight** [bazukas/obs-linuxbrowser#50]
For some reason when I have the obs-linuxbrowser in the .config folder OBS just wouldn't start. I've tried installing both version and none of them works.

I'm running Debian 9.3

**Comment by bazukas** [comment]
Hello, it seems like the binary release is not working on Debian for some reason.
Your best bet for now would be building the plugin yourself.

**Comment by SacredWKnight** [comment]
I tried building the plugin but I'm stuck on the `cmake -D CEF_DIR=<path to your cef dir> .. You might need to also set OBS_INCLUDE and/or OBS_LIB build variables` part. Do you mind clarifying how this is done?

**Comment by bazukas** [comment]
Did you try just running `cmake -D CEF_DIR=...`? set CEF_DIR to directory where you have extracted and built the CEF.

Post the log if not successful.

**Comment by SacredWKnight** [comment]
Tried, when I typed `make` after that this shows up:

```
~/Documents/2017/obs-linuxbrowser/build$ make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sacredwknight/Documents/2017/obs-linuxbrowser/build
[  7%] Building C object CMakeFiles/obs-linuxbrowser.dir/src/plugin/main.c.o
/home/sacredwknight/Documents/2017/obs-linuxbrowser/src/plugin/main.c:17:24: fatal error: obs-module.h: No such file or directory
 #include <obs-module.h>
                        ^
compilation terminated.
CMakeFiles/obs-linuxbrowser.dir/build.make:62: recipe for target 'CMakeFiles/obs-linuxbrowser.dir/src/plugin/main.c.o' failed
make[2]: *** [CMakeFiles/obs-linuxbrowser.dir/src/plugin/main.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/obs-linuxbrowser.dir/all' failed
make[1]: *** [CMakeFiles/obs-linuxbrowser.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by bazukas** [comment]
It seems that debian obs-studio package does not include development headers. I think what you should try is:
- clone obs-studio repository or download source tarball (git clone https://github.com/jp9000/obs-studio.git)
- run `cmake -D CEF_DIR=... -D OBS_INCLUDE=...`, set OBS_INCLUDE to obs-studio/libobs directory

**Comment by NexAdn** [comment]
https://packages.debian.org/search?keywords=libobs-dev

This should be the debian package containing the necessary development headers to compile obs-linuxbrowser.

**Comment by bazukas** [comment]
Closed due to lack of response
