### ISSUE TITLE
White Box streamlabs

### ISSUE THREAD

**Issue by reapsquad** [bazukas/obs-linuxbrowser#52]
I did everything correctly,but when I copied the streamlabs alert box in obs, instead of getting a preview all I got was a white box. When I did a test run from streamlabs it still worked properly, but the white box was still there. When I recorded/streamed, the box was still there.

**Comment by bazukas** [comment]
Hello. Could you please provide an obs log? Does the white box persist after restarting obs?

**Comment by reapsquad** [comment]
[2018-01-30 02-10-45.txt](https://github.com/bazukas/obs-linuxbrowser/files/1677185/2018-01-30.02-10-45.txt)
It does go away after restarting it so thats good, but kinda annoying to do it twice to get it working per different game you want to play.
