### ISSUE TITLE
Release is for old version of OBS

### ISSUE THREAD

**Issue by marouanopen** [bazukas/obs-linuxbrowser#55]
I'm running the latest version of Ubuntu and my OBS is version 21.1.0 but the release page latest version is build against OBS version 20.0.1, could we get it updated.
Also (perhaps requires separate issue) I will try building it for now but I do not know what to set OBS_INCLUDE and/or OBS_LIB variables to, excuse me for my ignorance but do I need to download some OBS library and set the location of that lib to the vars or are the libs already installed when I have OBS installed? Could you be more explicit in your readme on what to set the env vars as?
Anyway, love that you made this.

**Comment by NexAdn** [comment]
Normally the only thing you require is to install 'obs-studio-dev` or whatever the package with the OBS header files is named in Ubuntu (should be the name of the normal OBS Studio package plus `-dev`). This _should_ normally do the job. If not, see where the OBS header files are located (default is `/usr/include/obs`) and where the obs libraries are located (default is `/usr/lib`). Pass these paths to OBS_INCLUDE and OBS_LIB. And of course don't forget to have a version of CEF (minimal release or higher) ready and `libcef_dll_wrapper` compiled.

**Comment by NexAdn** [comment]
@marouanopen any results by now?

**Comment by maxdrash** [comment]
Hello, same problem here with Ubuntu 18.04, obs-studio 21.0.2 from ubuntu repos.
I tried to compile linux browser with the master branch and it still doesn't display a web page.
The plugin window remains black in the obs composer.

Please, have you a solution ?

**Comment by maxdrash** [comment]
Thank you for your answer.
I tried that version too and it's impossible.
I'll wait for a patch to come out ^^

**Comment by NexAdn** [comment]
https://drive.google.com/open?id=1hb130FTNy0a_sJlw4ph5dYb-8ND0ORMl

This is my current build of Linuxbrowser, but with #59 already applied, so it is not the `master` branch (but derived from it, so you have all features of upstream plus the additions of the PR). Normally you should be able to extract this archive as you do with the official Linuxbrowser binary releases.

**Comment by maxdrash** [comment]
Thank you, but there are 3 missing links in the zip : 
browser -> /opt/fpdata/AtomC++/obs-linuxbrowser-build/build/obs-linuxbrowser/bin/64bit/browser
browser-subprocess -> /opt/fpdata/AtomC++/obs-linuxbrowser-build/build/obs-linuxbrowser/bin/64bit/browser-subprocess
libobs-linuxbrowser.so -> /opt/fpdata/AtomC++/obs-linuxbrowser-build/build/obs-linuxbrowser/bin/64bit/libobs-linuxbrowser.so

I can't tell if it works without them ^^

**Comment by NexAdn** [comment]
No it doesn't. I set these links to easily test the plugin without having to install the plugin everytime I change something^^ I've just updated the archive file. You can still use the above link to download the new archive.

**Comment by maxdrash** [comment]
It's working! Thank you so much for your help :+1:

**Comment by NexAdn** [comment]
No problem. I suppose this issue can be closed now.

**Comment by maxdrash** [comment]
Yes i think
