### ISSUE TITLE
 --disable-web-security

### ISSUE THREAD

**Issue by MrTomek** [bazukas/obs-linuxbrowser#57]
Hello, is it possible to disable browser security, e.g.
as in chrome --disable-web-security, it would greatly facilitate my work

**Comment by bazukas** [comment]
Hello, have you tried adding that to the "Command line arguments" in properties?

**Comment by MrTomek** [comment]
I do not quite understand what you mean, you can direct me

**Comment by MrTomek** [comment]
If you want to run OBS with the --disable-web-security argument
Unfortunately, it was not working

**Comment by bazukas** [comment]
Open properties window of the browser source, scroll down, you'll see "Command-Line Arguments" option. Add a new entry "--disable-web-security" and click restart browser.

**Comment by MrTomek** [comment]
Ok, he works thanks to the master
