### ISSUE TITLE
I'm too stupid to understand your Readme: Building Plugin

### ISSUE THREAD

**Issue by networkcookie** [bazukas/obs-linuxbrowser#66]
so I've got to "Building Plugin" without problems, but the "cmake -D CEF_DIR=<path to your cef dir> .. You might need to also set OBS_INCLUDE and/or OBS_LIB build variables" is too much for my brain.
Where's my directory? is it in the Downloads cef-thing? Couldn't find another cef-thing

I'm sorry if I'm too stupid for that and idk if that's important but I'm running Debian9.

**Comment by NexAdn** [comment]
Did you download a binary release? If so, you just have to extract the contents of the archive to `$HOME/.config/obs-studio/plugins` and everything should be working out just fine.

If not, you first need to download a binary release of CEF (a link to the download page is in the readme. Download a version that is known to be working (see #63)). After downloading, extract the archive, cd into it and run `cmake .. && make libcef_dll_wrapper`. After that, you clone this repository with Git, cd into it and run `mkdir build && cd build`. 

The CEF_DIR must be set to the path where you extracted the downloaded CEF archive. If you extracted CEF to `/home/user/Downloads/cef_binary_WHATEVER`, the command is `cmake -DCEF_DIR=/home/user/Downlaods/cef_binary_WHATEVER ..` (notice the two dots at the end of the command). OBS_INCLUDE and OBS_LIB should normally stay unset as the default values are often times correct across most distributions. But make sure you installed the appropriate `-dev` package, if there is one. CMake should now run without errors, so you can execute `make && make install` to compile and install the plugin. Again, it's not necessary to build the plugin, if you've downloaded a binary release.

**Comment by networkcookie** [comment]
I've got a little problem with the cmake .. && make libcef_dll_wrapper because I've done it in the cef_binary in the Downloads folder.. how do I reverse it? 
I get the CMake Error: current directory is different from the directory CMakeCache.txt was created

**Comment by NexAdn** [comment]
My mistake. You have to run `cmake . && make` (single dot) when inside the cef directory.
