### ISSUE TITLE
Latest release version not listed on README

### ISSUE THREAD

**Issue by LuciousLisa** [bazukas/obs-linuxbrowser#72]
I see that [version 0.4.0](https://github.com/bazukas/obs-linuxbrowser/releases/tag/0.4.0) uses OBS 21.1.1, but [on the README page](https://github.com/bazukas/obs-linuxbrowser/commit/27df7730648f53773ff5df1c24eb6e2acd621652#diff-04c6e90faac2675aa89e2176d2eec7d8L14) it still says that the current OBS version used to build the plugin with is 20.0.1  
  
I am using Chromium 67.0.3396.87 and OBS 21.1.1 on Debian 9:

```10:48:46.732: CPU Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
10:48:46.732: CPU Speed: 4199.951MHz
10:48:46.733: Physical Cores: 4, Logical Cores: 8
10:48:46.733: Physical Memory: 15995MB Total, 1003MB Free
10:48:46.733: Kernel Version: Linux 4.9.0-6-amd64
10:48:46.733: Distribution: "Debian GNU/Linux" "9"
10:48:46.733: Portable mode: false
10:48:46.742: OBS 21.1.1 (linux)
```  
Can you please confirm that it is safe to use version 0.4.0 of the plugin with that OBS version and that it should be expected to work with that Chromium version? Thanks so much!

**Comment by NexAdn** [comment]
0.4.0 has been compiled for OBS version 21.1. The obs version which the release has been compiled for, is part of the file name of the binary release.

**Comment by NexAdn** [comment]
Updated README to use the most recent version number.
