### ISSUE TITLE
Wrong keymappings / jQuery keypress events not working properly

### ISSUE THREAD

**Issue by Francexi** [bazukas/obs-linuxbrowser#82]
JQuery keydown event doesn't seems to run properly. I don't have any idea of how to debug this

EDIT: Checking the console log, I've noticed that actually, they key is registered (I used keypress instead of keydown) but the number of the key is totally wrong

Here I pressed first a "h" then "Esc" and I made the browser console.log(event.key);

`info: obs-linuxbrowser: Key: h 104 43
[0824/152604.156298:INFO:CONSOLE(107)] "8", source: http://localhost/praesidium/featured/ (107)
info: obs-linuxbrowser: Key: h 104 43
info: obs-linuxbrowser: Key: 65307 9
[0824/152611.726724:WARNING:keyboard_code_conversion_x.cc(1438)] Unknown keycode:65307
[0824/152611.728842:INFO:CONSOLE(107)] "", source: http://localhost/praesidium/featured/ (107)
info: obs-linuxbrowser: Key: 65307 9
[0824/152611.800328:WARNING:keyboard_code_conversion_x.cc(1438)] Unknown keycode:65307`

I've checked the Key code tables, and, for some reason, the h key is mapped as 104 (where 104 is actually a 8 from the keypress/keydown event)

EDIT x2:
after a bit of tries, I've figured the following:
-the plugin passes the Qt provided nativeVirtualKey to the CEF
-Qt provides the ASCII code of the key as nativeVirtualKey. That seems to be consistent with the CEF ones only for uppercase characters and numbers
-Escape and other "Meta" keys has a big number as nativeVirtualKey, I'm still trying to get what that number means

**Comment by NexAdn** [comment]
Thank you for reporting this bug. I'll try to fix that for you as soon as I have time for it. If you have more resources that might help me resolve this issue, please share it with me.

**Comment by Francexi** [comment]
First of all, I need to now if the bug is distro-dependant. Can you kindly try to reproduce it?
________________________________

**Comment by Francexi** [comment]
I found the source of the bug. And is CEF-related.

Basically, CEF uses Windows Keycodes (VK_) while on linux the codes are XKB (pretty different).
I've made a mapping, I will make a Pull request later this day or tomorrow

**Comment by NexAdn** [comment]
Thank your for your PR, but I think there is an easier solution.

https://github.com/bazukas/obs-linuxbrowser/blob/94baeade2be1a862d4af552b0968d88aab8d0277/src/browser/browser-app.cpp#L197-L198

As you see, bazukas duplicated the native vkey to the windows vkey (that's what you already noticed). I am not sure if it's possible to just remove this Windows keycode setting / leaving it empty. I am not at home right now, so I can't test it myself, but maybe you can try to remove the above line 197. If that's working, it would be way more elegant than a manual remapping (an possibly more efficient).

**Comment by Francexi** [comment]
I probably will not be able to do it today. Anyway, I hardly believe that will work, but giving a try is never a bad thing, isn't it?

**Comment by NexAdn** [comment]
I think what bazukas did was on purpose (see the comment above) in the sense that it is somehow needed to pass a windows keycode as well, but yeah, it's worth a try as it is really nothing but removing one single line.

I will do a quick review of your PR now, in case the above solution doesn't work, but as I already said, I'm unable to test it right now.
